# Tensor Basics

Tensors are multidimensional arrays with a uniform data type

Tensors are kinda like np.arrays

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

# The biggest difference between a numpy array and a PyTorch Tensor is that a PyTorch Tensor can run on either CPU or GPU.

In [32]:
import torch

In [33]:
torch.cuda.is_available()

True

In [34]:
x = torch.empty(3)
print(x) # vector with 3 elements.....One axis

tensor([2.2278e+23, 7.9086e-41, 2.2276e+23])


In [35]:
x = torch.empty(2,3, dtype = torch.int32, device = 'cuda')
print(x) # vector with 6 elements.....two axis

tensor([[0, 0, 0],
        [0, 0, 0]], device='cuda:0', dtype=torch.int32)


In [36]:
x = torch.empty(2,3, dtype = torch.int32)
print(x) # vector with 6 elements.....two axis

tensor([[ 875979361, 1647601200,  809066804],
        [1664104761, 1684431922,  811950643]], dtype=torch.int32)


In [37]:
# random numbers
x = torch.rand(2,2)
x

tensor([[0.9893, 0.7110],
        [0.4602, 0.7828]])

In [39]:
# Zeroes
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [40]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [42]:
x.dtype

torch.float32

In [48]:
x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)
x

torch.int32


tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [49]:
# check size/shape
x.size()

torch.Size([2, 2])

In [51]:
# Making tensors out of lists...
x = torch.tensor([1,2,3,4,5], dtype=torch.double)
x

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)

In [54]:
# Addition
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
z

tensor([[0.1314, 0.2526],
        [0.7642, 0.5139]])
tensor([[0.3748, 0.7794],
        [0.5591, 0.8655]])


tensor([[0.5061, 1.0320],
        [1.3233, 1.3794]])

In [55]:
# Addition
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.add(x,y)
z

tensor([[0.8846, 0.2285],
        [0.9029, 0.0698]])
tensor([[0.5240, 0.3187],
        [0.1058, 0.8288]])


tensor([[1.4086, 0.5472],
        [1.0087, 0.8986]])

In [57]:
# Addition
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
y.add_(x)    # The underscore refers to inplace function...
y

tensor([[0.5683, 0.3111],
        [0.2257, 0.5844]])
tensor([[0.9750, 0.9691],
        [0.6552, 0.0774]])


tensor([[1.5433, 1.2802],
        [0.8809, 0.6618]])

In [59]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:,0])

tensor([[0.3195, 0.9320, 0.0961],
        [0.8054, 0.8461, 0.2258],
        [0.5114, 0.7730, 0.4803],
        [0.1763, 0.8383, 0.9299],
        [0.8535, 0.3212, 0.1133]])
tensor([0.3195, 0.8054, 0.5114, 0.1763, 0.8535])


In [61]:
# Reshaping tensors...
x = torch.rand(4,4)
print(x)

y = x.view(16) # One dimension....(Flatten)
print(y)

tensor([[0.9790, 0.7702, 0.7494, 0.3355],
        [0.2507, 0.1933, 0.2376, 0.2772],
        [0.3099, 0.1891, 0.1159, 0.8538],
        [0.7941, 0.5828, 0.2631, 0.4710]])
tensor([0.9790, 0.7702, 0.7494, 0.3355, 0.2507, 0.1933, 0.2376, 0.2772, 0.3099,
        0.1891, 0.1159, 0.8538, 0.7941, 0.5828, 0.2631, 0.4710])


In [63]:
# Reshaping tensors... automatic determination of size based on one shape value...
x = torch.rand(4,4)
print(x)

y = x.view(-1, 8) # One dimension....(Flatten)
print(y)
print(y.size())

tensor([[0.2876, 0.8867, 0.7140, 0.5048],
        [0.6770, 0.2695, 0.0191, 0.5608],
        [0.6963, 0.5055, 0.1262, 0.2259],
        [0.8143, 0.7827, 0.4633, 0.0235]])
tensor([[0.2876, 0.8867, 0.7140, 0.5048, 0.6770, 0.2695, 0.0191, 0.5608],
        [0.6963, 0.5055, 0.1262, 0.2259, 0.8143, 0.7827, 0.4633, 0.0235]])
torch.Size([2, 8])


In [68]:
# Converting numpy to torch tensor and vice-versa...
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))
print('\n\n--------------------')

# Sidenote - If the tensor is on the CPU and not the GPU, then both objects (a and b) will share the 
# same memory location....so you change one, you also change the other...


a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


--------------------
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [70]:
# Converting torch tensor to numpy...
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
print(type(b))

print('\n\n--------------------')


a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


--------------------
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [83]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    print(z)
    
    
# you cannot convert a GPU tensor back to numpy 

tensor([2., 2., 2., 2., 2.], device='cuda:0')
